bot :
  FINDER_BOT_TOKEN : 7997305007:AAGTSv7aUYPnPsOcEEl5H0JF8meNQ4fdhrs
  MESSANGER_BOT_TOKEN : 7826683135:AAHMBbzyTbLSK6M_DsN2gLChIGmEHfaFOgU
  ADMINS : 826729843|1333226032

paths :
  DB_HOST : localhost
  DB_USER : root
  DB_PASSWORD : 1Qa2Ws3Ed
  DB_NAME : fake_tinder

api :
  weather_api : 14b0adbe26638f615623050b9f0d29bb